import { createHash } from "crypto";
import sharp from "sharp";
import { PutObjectCommand, GetObjectCommand, DeleteObjectCommand } from "@aws-sdk/client-s3";
import { v4 as uuidv4 } from "uuid";
import s3Client from "../../config/s3";
import Product, { IProductSchema } from "../../model/Product";
import RoomVisualization, { IRoomVisualization, RenderErrorKind } from "../../model/RoomVisualization";
import { buildFloorPrompt } from "./prompt";
import { renderWithOpenAI, RenderOutput, openAIConfig, ProviderCanvas } from "./providers/openaiProvider";
import { estimateCostUsd } from "./pricing";

/*
 * Privacy model
 * -------------
 * Customer photos are never written to disk, S3 or the database. `renderCustomerPhoto`
 * keeps the photo in memory for the duration of the request, sends it to the AI
 * provider, returns the result to the caller and records only statistics.
 *
 * Sample rooms (uploaded or generated by an admin) are stored in S3, and their
 * renders are cached in S3 so a (sample, product) pair is paid for once.
 */

const ROOM_MAX_SIDE = Number(process.env.VISUALIZER_ROOM_MAX_SIDE || 1536);
const REF_MAX_SIDE = 1024;
// How many product photos are sent as references (each one costs input tokens).
const REFERENCE_IMAGES = Math.max(1, Math.min(3, Number(process.env.VISUALIZER_REFERENCE_IMAGES || 2)));
const BUCKET = process.env.AWS_S3_BUCKET || "";
const REGION = process.env.AWS_REGION || "";

// Short-lived in-memory cache of customer results so that "try another design → back"
// or a quick retry doesn't pay for the same (photo, product) twice.
const RESULT_CACHE_TTL_MS = Number(process.env.VISUALIZER_RESULT_CACHE_TTL_MS || 15 * 60 * 1000);
const RESULT_CACHE_MAX = 40;

type Source = "customer" | "admin" | "cli";

const s3Url = (key: string) => `https://${BUCKET}.s3.${REGION}.amazonaws.com/${key}`;

const putObject = async (key: string, body: Buffer, contentType: string) => {
  await s3Client.send(new PutObjectCommand({ Bucket: BUCKET, Key: key, Body: body, ContentType: contentType }));
  return s3Url(key);
};

const deleteObject = async (key?: string) => {
  if (!key) return;
  try {
    await s3Client.send(new DeleteObjectCommand({ Bucket: BUCKET, Key: key }));
  } catch (e) {
    console.warn("[visualizer] cannot delete", key, e);
  }
};

/** Raw S3 stream for proxied downloads (the bucket has no CORS, so the browser can't fetch it directly). */
export const getObjectStream = async (key: string) => {
  const res = await s3Client.send(new GetObjectCommand({ Bucket: BUCKET, Key: key }));
  return { body: res.Body as NodeJS.ReadableStream, contentType: res.ContentType || "image/jpeg", contentLength: res.ContentLength };
};

const getObject = async (key: string): Promise<Buffer> => {
  const res = await s3Client.send(new GetObjectCommand({ Bucket: BUCKET, Key: key }));
  const bytes = await res.Body!.transformToByteArray();
  return Buffer.from(bytes);
};

const fetchBuffer = async (url: string): Promise<{ buffer: Buffer; mime: string }> => {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Cannot download ${url}: ${res.status}`);
  const mime = res.headers.get("content-type") || "image/jpeg";
  return { buffer: Buffer.from(await res.arrayBuffer()), mime };
};

// HEIC/HEIF (iPhone photos) use the HEVC codec, which the bundled libvips cannot decode.
// The container starts with "....ftyp" followed by a brand such as heic, heix, hevc, mif1, msf1.
const isHeif = (buf: Buffer) => buf.length > 12 && buf.toString("ascii", 4, 8) === "ftyp" && /^(heic|heix|hevc|hevx|heim|heis|mif1|msf1)$/.test(buf.toString("ascii", 8, 12));

/** Decodes HEIC/HEIF to JPEG with the pure-JS libheif build (slow-ish, ~1–3 s, but works everywhere). */
const heifToJpeg = async (input: Buffer): Promise<Buffer> => {
  const { default: convert } = await import("heic-convert");
  const out = await convert({ buffer: input, format: "JPEG", quality: 0.92 });
  return Buffer.isBuffer(out) ? out : Buffer.from(out as ArrayBuffer);
};

const normalise = (input: Buffer, maxSide: number) =>
  sharp(input).rotate().resize({ width: maxSide, height: maxSide, fit: "inside", withoutEnlargement: true }).jpeg({ quality: 88 }).toBuffer();

/** Normalises a photo: fixes EXIF rotation, caps the size, re-encodes as JPEG (this also strips EXIF/GPS metadata). */
export const prepareRoomImage = async (input: Buffer): Promise<Buffer> => {
  if (isHeif(input)) return normalise(await heifToJpeg(input), ROOM_MAX_SIDE);
  try {
    return await normalise(input, ROOM_MAX_SIDE);
  } catch (err) {
    // Some HEIF files carry unusual brands; give the decoder one more chance before giving up.
    if (input.toString("ascii", 4, 8) === "ftyp") return normalise(await heifToJpeg(input), ROOM_MAX_SIDE);
    throw err;
  }
};

const prepareReference = async (input: Buffer): Promise<Buffer> =>
  sharp(input).rotate().resize({ width: REF_MAX_SIDE, height: REF_MAX_SIDE, fit: "inside", withoutEnlargement: true }).jpeg({ quality: 88 }).toBuffer();

/** Stores a prepared sample room photo and registers it (admin only). */
export const createSampleRoom = async (file: Buffer, opts: { title?: string; source?: Source } = {}) => {
  const prepared = await prepareRoomImage(file);
  const roomKey = `rooms/samples/${uuidv4()}.jpg`;
  const roomUrl = await putObject(roomKey, prepared, "image/jpeg");
  return RoomVisualization.create({
    roomKey,
    roomUrl,
    isSample: true,
    isActive: true,
    title: opts.title,
    status: "room",
    source: opts.source || "admin",
  });
};

/** Text-to-image for sample rooms (admin tool). */
export const generateSampleImage = async (prompt: string): Promise<Buffer> => {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) throw new Error("OPENAI_API_KEY is not set");
  const { model, quality } = openAIConfig();
  const res = await fetch("https://api.openai.com/v1/images/generations", {
    method: "POST",
    headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
    body: JSON.stringify({ model, prompt, size: "1536x1024", quality, output_format: "jpeg" }),
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`OpenAI ${res.status}: ${text.slice(0, 300)}`);
  return Buffer.from(JSON.parse(text).data[0].b64_json, "base64");
};

export const DEFAULT_SAMPLE_PROMPT =
  "Photo of an empty modern living room in an Israeli apartment, taken with a phone from standing height, daylight from a large window, white walls, old plain grey ceramic tile floor clearly visible, a sofa against the wall, no people, no text.";

const providers: Record<string, (i: Parameters<typeof renderWithOpenAI>[0]) => Promise<RenderOutput>> = {
  openai: renderWithOpenAI,
};

export const providerName = () => process.env.VISUALIZER_PROVIDER || "openai";

/** Public description of the current generation setup (shown in the admin dashboard). */
export const visualizerConfig = () => {
  const { model, quality, inputFidelity } = openAIConfig();
  return { provider: providerName(), model, quality, inputFidelity, referenceImages: REFERENCE_IMAGES, roomMaxSide: ROOM_MAX_SIDE };
};

export const classifyError = (err: unknown): RenderErrorKind => {
  const e = err as { name?: string; message?: string; kind?: RenderErrorKind };
  if (e?.kind) return e.kind;
  const message = String(e?.message || err);
  if (e?.name === "AbortError" || /abort|timed? ?out/i.test(message)) return "timeout";
  if (/^OpenAI \d{3}/.test(message)) return "provider";
  if (/input buffer|unsupported image|corrupt|bad image/i.test(message)) return "image";
  return "internal";
};

/* ------------------------------ framing ------------------------------
 * The provider only outputs 3:2, 2:3 or 1:1 canvases, while phones shoot 4:3. Instead of
 * cropping the customer's photo we pad it to the nearest canvas with mirrored edges, let the
 * model work on the padded picture, then cut the original frame back out of the result.
 * The shopper gets their whole photo back, in its own aspect ratio, nothing lost.
 */
interface Framing {
  image: Buffer;          // padded image sent to the provider
  size: ProviderCanvas;
  paddedWidth: number;
  paddedHeight: number;
  left: number;           // where the original sits inside the padded image
  top: number;
  width: number;
  height: number;
}

const CANVASES: { size: ProviderCanvas; ratio: number }[] = [
  { size: "1536x1024", ratio: 1.5 },
  { size: "1024x1536", ratio: 2 / 3 },
  { size: "1024x1024", ratio: 1 },
];

export const fitToProviderCanvas = async (input: Buffer): Promise<Framing> => {
  const { width, height } = await sharp(input).metadata();
  if (!width || !height) throw new Error("Cannot read image size");
  const ratio = width / height;
  // Nearest canvas by the amount of padding needed (compare log-ratios so 4:3 and 3:4 are symmetric).
  const canvas = CANVASES.reduce((best, c) => (Math.abs(Math.log(c.ratio / ratio)) < Math.abs(Math.log(best.ratio / ratio)) ? c : best));

  let paddedWidth = width;
  let paddedHeight = height;
  if (ratio < canvas.ratio) paddedWidth = Math.round(height * canvas.ratio);
  else paddedHeight = Math.round(width / canvas.ratio);
  const left = Math.floor((paddedWidth - width) / 2);
  const top = Math.floor((paddedHeight - height) / 2);

  const image =
    paddedWidth === width && paddedHeight === height
      ? input
      : await sharp(input)
          .extend({ left, right: paddedWidth - width - left, top, bottom: paddedHeight - height - top, extendWith: "mirror" })
          .jpeg({ quality: 88 })
          .toBuffer();

  return { image, size: canvas.size, paddedWidth, paddedHeight, left, top, width, height };
};

/** Cuts the original photo's frame back out of the provider's result. */
export const restoreFraming = async (result: Buffer, framing: Framing): Promise<Buffer> => {
  if (framing.left === 0 && framing.top === 0 && framing.paddedWidth === framing.width && framing.paddedHeight === framing.height) return result;
  const meta = await sharp(result).metadata();
  const sx = (meta.width || framing.paddedWidth) / framing.paddedWidth;
  const sy = (meta.height || framing.paddedHeight) / framing.paddedHeight;
  const left = Math.round(framing.left * sx);
  const top = Math.round(framing.top * sy);
  const width = Math.min(Math.round(framing.width * sx), (meta.width || 0) - left);
  const height = Math.min(Math.round(framing.height * sy), (meta.height || 0) - top);
  return sharp(result).extract({ left, top, width, height }).jpeg({ quality: 90 }).toBuffer();
};

/** Calls the AI provider for one (room image, product) pair. No storage involved. */
const runRender = async (roomImage: Buffer, product: IProductSchema): Promise<RenderOutput> => {
  const render = providers[providerName()];
  if (!render) throw new Error(`Unknown visualizer provider: ${providerName()}`);
  const framing = await fitToProviderCanvas(roomImage);

  const refs = await Promise.all(product.images.slice(0, REFERENCE_IMAGES).map((url) => fetchBuffer(url)));
  const referenceImages = await Promise.all(refs.map(async (r) => ({ buffer: await prepareReference(r.buffer), mime: "image/jpeg" })));
  const prompt = buildFloorPrompt({
    name: product.name?.en || (product.name as unknown as string),
    category: product.category,
    color: product.color,
    type: product.type,
    material: product.material,
    finish: product.finish,
    width: product.width,
    length: product.length,
  });

  const out = await render({ roomImage: framing.image, roomMime: "image/jpeg", referenceImages, prompt, size: framing.size });
  return { ...out, image: await restoreFraming(out.image, framing) };
};

/** Fills a render record from the provider output. */
const applyOutput = (record: IRoomVisualization, out: RenderOutput, started: number) => {
  record.set({
    status: "done",
    aiModel: out.model,
    quality: out.quality,
    usage: out.usage,
    estimatedCostUsd: estimateCostUsd(out.model, out.usage),
    durationMs: Date.now() - started,
  });
};

const applyFailure = (record: IRoomVisualization, err: unknown, started: number) => {
  record.set({
    status: "failed",
    error: String((err as Error)?.message || err).slice(0, 1000),
    errorKind: classifyError(err),
    durationMs: Date.now() - started,
  });
};

/* ------------------------------ customer photos ------------------------------ */

interface CachedResult { image: Buffer; mime: string; expires: number }
const resultCache = new Map<string, CachedResult>();

const cacheKey = (prepared: Buffer, productId: string) => `${createHash("sha256").update(prepared).digest("hex")}:${productId}`;

const cacheGet = (key: string) => {
  const hit = resultCache.get(key);
  if (!hit) return undefined;
  if (hit.expires < Date.now()) { resultCache.delete(key); return undefined; }
  return hit;
};

const cacheSet = (key: string, value: Omit<CachedResult, "expires">) => {
  const now = Date.now();
  for (const [k, v] of resultCache) if (v.expires < now) resultCache.delete(k);
  while (resultCache.size >= RESULT_CACHE_MAX) resultCache.delete(resultCache.keys().next().value as string);
  resultCache.set(key, { ...value, expires: now + RESULT_CACHE_TTL_MS });
};

export interface CustomerRenderResult {
  image: Buffer;
  mime: string;
  durationMs: number;
  cached: boolean;
}

/** Writes a failed record for an upload that never reached the AI (bad file, too large), so the admin can see it. */
export const recordRejectedUpload = async (message: string, ip?: string, productId?: string) => {
  try {
    await RoomVisualization.create({
      isSample: false,
      productId,
      provider: providerName(),
      status: "failed",
      errorKind: "image",
      error: message.slice(0, 1000),
      durationMs: 0,
      ip,
      source: "customer",
    });
  } catch (e) {
    console.warn("[visualizer] cannot record rejected upload", e);
  }
};

/**
 * Renders a product floor into a customer's photo without storing the photo or the result.
 * Only a statistics record (no images) is written to the database.
 */
export const renderCustomerPhoto = async (photo: Buffer, productId: string, opts: { ip?: string } = {}): Promise<CustomerRenderResult> => {
  const started = Date.now();
  let prepared: Buffer;
  try {
    prepared = await prepareRoomImage(photo);
  } catch (err) {
    const detail = String((err as Error)?.message || err);
    console.warn("[visualizer] cannot decode photo:", detail, { ip: opts.ip, bytes: photo.length });
    await recordRejectedUpload(`Cannot decode photo (${photo.length} bytes): ${detail}`, opts.ip, productId);
    throw Object.assign(new Error("Unsupported or corrupt image"), { status: 400, kind: "image" as RenderErrorKind });
  }

  const key = cacheKey(prepared, productId);
  const hit = cacheGet(key);
  if (hit) return { image: hit.image, mime: hit.mime, durationMs: Date.now() - started, cached: true };

  const product = await Product.findById(productId);
  if (!product) throw Object.assign(new Error("Product not found"), { status: 404 });

  const record = await RoomVisualization.create({
    isSample: false,
    productId,
    provider: providerName(),
    status: "pending",
    ip: opts.ip,
    source: "customer",
  });

  try {
    const out = await runRender(prepared, product);
    applyOutput(record, out, started);
    await record.save();
    cacheSet(key, { image: out.image, mime: out.mime });
    return { image: out.image, mime: out.mime, durationMs: Date.now() - started, cached: false };
  } catch (err) {
    applyFailure(record, err, started);
    await record.save();
    throw err;
  }
};

/* ------------------------------- sample rooms -------------------------------- */

/** Renders a product floor into a sample room. Cached in S3 per (room, product) unless `force`. */
export const renderRoom = async (roomKey: string, productId: string, opts: { ip?: string; source?: Source; force?: boolean } = {}): Promise<IRoomVisualization> => {
  if (!opts.force) {
    const cached = await RoomVisualization.findOne({ roomKey, productId, status: "done" });
    if (cached) return cached;
  }

  const room = await RoomVisualization.findOne({ roomKey, status: "room", isSample: true });
  if (!room) throw Object.assign(new Error("Room not found"), { status: 404 });

  const product = await Product.findById(productId);
  if (!product) throw Object.assign(new Error("Product not found"), { status: 404 });

  const record = await RoomVisualization.create({
    roomKey,
    roomUrl: room.roomUrl,
    isSample: true,
    productId,
    provider: providerName(),
    status: "pending",
    ip: opts.ip,
    source: opts.source || "customer",
  });

  const started = Date.now();
  try {
    const roomImage = await getObject(roomKey);
    const out = await runRender(roomImage, product);
    const resultKey = `${roomKey.replace(/\.jpg$/, "")}/${productId}-${Date.now().toString(36)}.jpg`;
    const resultUrl = await putObject(resultKey, out.image, out.mime);
    applyOutput(record, out, started);
    record.set({ resultKey, resultUrl });
    await record.save();
    return record;
  } catch (err) {
    applyFailure(record, err, started);
    await record.save();
    throw err;
  }
};

/** Admin: drop a sample render (S3 + record) and run it again. Older renders for the pair are removed too. */
export const regenerateRender = async (renderId: string) => {
  const render = await RoomVisualization.findById(renderId);
  if (!render || !render.productId || !render.roomKey || !render.isSample) {
    throw Object.assign(new Error("Only sample-room renders can be regenerated"), { status: 404 });
  }
  const { roomKey, productId } = render;
  const siblings = await RoomVisualization.find({ roomKey, productId, status: { $in: ["done", "failed"] } });
  for (const doc of siblings) {
    await deleteObject(doc.resultKey);
    await doc.deleteOne();
  }
  return renderRoom(roomKey, productId, { source: "admin", force: true });
};

export const deleteRender = async (renderId: string) => {
  const render = await RoomVisualization.findById(renderId);
  if (!render || render.status === "room") throw Object.assign(new Error("Render not found"), { status: 404 });
  await deleteObject(render.resultKey);
  await render.deleteOne();
};

/** Admin: delete a sample room together with everything rendered from it. */
export const deleteRoom = async (roomId: string) => {
  const room = await RoomVisualization.findById(roomId);
  if (!room || room.status !== "room") throw Object.assign(new Error("Room not found"), { status: 404 });
  const renders = await RoomVisualization.find({ roomKey: room.roomKey, status: { $ne: "room" } });
  for (const doc of renders) {
    await deleteObject(doc.resultKey);
    await doc.deleteOne();
  }
  await deleteObject(room.roomKey);
  await room.deleteOne();
};

/* ------------------------------ one-time cleanup ------------------------------ */

const legacyCustomerFilter = { isSample: false, $or: [{ roomKey: { $exists: true } }, { resultKey: { $exists: true } }] };

/** How many customer images from before the privacy change are still stored. */
export const countStoredCustomerImages = () => RoomVisualization.countDocuments(legacyCustomerFilter);

/**
 * Deletes every customer photo and customer result stored before the privacy change.
 * Room records are removed; render records are kept for statistics but stripped of images.
 */
export const purgeStoredCustomerImages = async () => {
  let files = 0;
  let rooms = 0;
  let renders = 0;

  const docs = await RoomVisualization.find(legacyCustomerFilter);
  for (const doc of docs) {
    if (doc.status === "room") {
      await deleteObject(doc.roomKey); files += 1;
      await doc.deleteOne(); rooms += 1;
    } else {
      if (doc.resultKey) { await deleteObject(doc.resultKey); files += 1; }
      await RoomVisualization.updateOne({ _id: doc._id }, { $unset: { roomKey: 1, roomUrl: 1, resultKey: 1, resultUrl: 1 } });
      renders += 1;
    }
  }
  return { files, rooms, renders };
};
